// SETTINGS CONSTANTS
export const LOGO_BG = "LOGO_BG";
export const NAVBAR_BG = "NAVBAR_BG";
export const SIDEBAR_BG = "SIDEBAR_BG";
export const THEME = "THEME";
export const DIRECTION = "DIRECTION";
export const SIDEBAR_POSITION = "SIDEBAR_POSITION";
export const HEADER_POSITION = "HEADER_POSITION";
export const LAYOUT = "LAYOUT";
export const SIDEBAR_TYPE = "SIDEBAR_TYPE";

// USER CONSTANTS
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const USER_LOADING = "USER_LOADING";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_ADDRESS = "FETCH_USER_ADDRESS";
export const ADD_USER_ADDRESS = "ADD_USER_ADDRESS";
export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS";
export const UPDATE_USER_TIMEZONE = "UPDATE_USER_TIMEZONE";



// STORES CONSTANTS
export const FETCH_STORE_SUCCESS = "FETCH_STORE_SUCCESS";
export const SELECT_STORE = "SELECT_STORE";
export const SELECT_USER = "SELECT_USER";

// ORDER CONSTANTS
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const ORDER_LOADING = "ORDER_LOADING";
export const SELECT_USER_ADDRESS = "SELECT_USER_ADDRESS";
export const SET_DELIVERY_TYPE = "SET_DELIVERY_TYPE";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const SET_SALES_TYPE = "SET_SALES_TYPE";
export const ORDER_HISTORY = "ORDER_HISTORY";
export const ORDER_CANCEL = "ORDER_CANCEL";
export const PROCESS_ORDER = "PROCESS_ORDER";
export const FETCH_PACKAGING = "FETCH_PACKAGING";
export const UPDATE_STOCK_STORE = "UPDATE_STOCK_STORE";
export const PICK_UP_STORE = "PICK_UP_STORE";
export const SET_FILTER_STORE_ID = "SET_FILTER_STORE_ID";
export const SET_HTO_APPIONTMENT_NO = 'SET_HTO_APPIONTMENT_NO';
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
export const APPLIED_DISCOUNT_VOUCHER = "APPLIED_DISCOUNT_VOUCHER";
export const DISCOUNTED_CART_AMOUNT = "DISCOUNTED_CART_AMOUNT";
export const UPDATE_DELIVERY_ADDRESS = "UPDATE_DELIVERY_ADDRESS";
export const REDEEMED_COFFEE = "REDEEMED_COFFEE";

// FRAME CONSTANTS
export const FETCH_FRAMES_SUCCESS = "FETCH_FRAMES_SUCCESS";
export const FRAME_DETAIL = "FRAME_DETAIL";
export const SELECT_FRAME = "SELECT_FRAME";

// CART CONSTANTS
export const GET_CART = "GET_CART";
export const ADD_CART = "ADD_CART";
export const CART_LOADING = "CART_LOADING";
export const DELETE_CART = "DELETE_CART";
export const DELETE_CART_ADDON = "DELETE_CART_ADDON";
export const FETCH_CART_ADDON = "FETCH_CART_ADDON";
export const EMPTY_CART = "EMPTY_CART";
export const SET_ITEM_WARRANTY = "SET_ITEM_WARRANTY";
export const UPDATE_PRESCRIPTION_DETAIL = "UPDATE_PRESCRIPTION_DETAIL";
export const LENSES_ONLY_DISCOUNT = "LENSES_ONLY_DISCOUNT";
export const GET_CART_CLIPON = "GET_CART_CLIPON";
export const UPDATE_CART_PACKAGING  = "UPDATE_CART_PACKAGING";

// LENSES CONSTANTS
export const FETCH_LENSES_SUCCESS = "FETCH_LENSES_SUCCESS";

// PRESCRIPTION CONSTANTS
export const FETCH_PRESCRIPTION_SUCCESS = "FETCH_PRESCRIPTION_SUCCESS";
export const ADD_PRESCRIPTION = "ADD_PRESCRIPTION";
export const PRESCRIPTION_LOADING = "PRESCRIPTION_LOADING";
export const UPDATE_PRESCRIPTION = "UPDATE_PRESCRIPTION";

// BANK CONSTANTS
export const FETCH_BANK_LIST = "FETCH_BANK_LIST";

// ANALYTICS CONSTANTS
export const FETCH_ANALYTICS_LIST = "FETCH_ANALYTICS_LIST";
export const ANALYTICS_LOADING = "ANALYTICS_LOADING";



// PERFORMANCE CONSTANTS
export const ORDERS_LOADING = "ORDERS_LOADING";
export const FETCH_APPOINTMENT_LIST = "FETCH_APPOINTMENT_LIST";
export const FETCH_ORDERS_LIST = "FETCH_ORDERS_LIST";
export const FETCH_SUMMARY = "FETCH_SUMMARY";
export const FETCH_GRAPHICAL_DATA = "FETCH_GRAPHICAL_DATA";
export const GRAPH_LOADING = 'GRAPH_LOADING';

// DASHBOARD CONSTANTS
export const FETCH_DASHBOARD_DATA = "FETCH_DASHBOARD_DATA";
export const DASHBOARD_LOADING = "DASHBOARD_LOADING";

//CUSTOMER CONSTANTS
export const FETCH_USER_LIST = "FETCH_USER_LIST";
export const CUSTOMER_LOADING = "CUSTOMER_LOADING";
export const CUSTOMER_DETAIL = "CUSTOMER_DETAIL";
export const DELETE_USER_ADDRESS = "DELETE_USER_ADDRESS";
export const UPDATE_CUSTOMER_PRESCRIPTION = "UPDATE_CUSTOMER_PRESCRIPTION";
export const DELETE_CUSTOMER_PRESCRIPTION = "DELETE_CUSTOMER_PRESCRIPTION";
export const ADD_CUSTOMER_PRESCRIPTION = "ADD_CUSTOMER_PRESCRIPTION";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

//CLIPON  CONSTANTS
export const  FETCH_CLIPON_SUCCESS  = 'FETCH_CLIPON_SUCCESS';

//HTO CONSTANTS 
export const FETCH_HTO_ORDER = 'FETCH_HTO_ORDER';
export const HTO_LOADING = 'HTO_LOADING';
export const HTO_ORDER_DETAIL = 'HTO_ORDER_DETAIL';
export const SELECT_HTO_USER = 'SELECT_HTO_USER';
export const SELECT_HTO_USER_ADDRESS = 'SELECT_HTO_USER_ADDRESS'; 
export const FETCH_HTO_USER_ADDRESS = 'FETCH_HTO_USER_ADDRESS';
export const GET_HTO_TIME_SLOT = 'GET_HTO_TIME_SLOT';
export const GET_OPTICIAN_LIST = 'GET_OPTICIAN_LIST';
export const CLEAR_HTO_DETAIL = 'CLEAR_HTO_DETAIL';
export const GET_INPUT_PERSON_LIST = 'GET_INPUT_PERSON_LIST';
export const GET_OPTICIAN_APPIONTMENTS_LIST = 'GET_OPTICIAN_APPIONTMENTS_LIST';

//discount constant
export const GET_DISCOUNT_CATEGORIES_LIST = 'GET_DISCOUNT_CATEGORIES_LIST';
export const GET_SKU_LIST = 'GET_SKU_LIST';
export const DISCOUNT_LOADING = 'DISCOUNT_LOADING';
export const GET_VOUCHER_LIST = 'GET_VOUCHER_LIST';
export const GET_VOUCHER_DETAIL = 'GET_VOUCHER_DETAIL';
export const SET_INACTIVE_LIST_VOUCHER = 'SET_INACTIVE_LIST_VOUCHER';
export const SET_INACTIVE_VIEW_VOUCHER = 'SET_INACTIVE_VIEW_VOUCHER';

//CONTACT LENSES CONSTANTS
export const FETCH_CONTACT_LENSES = "FETCH_CONTACT_LENSES";

//OTHER PRODUCT CONSTANTS
export const FETCH_OTHER_PRODUCT = "FETCH_OTHER_PRODUCT";

// User Management Constants
export const FETCH_ADMIN_USERS_SUCCESS = 'FETCH_ADMIN_USERS_SUCCESS';
export const USER_MANAGEMENT_LOADING = 'USER_MANAGEMENT_LOADING';
export const SET_USER_ID = 'SET_USER_ID';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';
export const GET_ROLES = 'GET_ROLES';

// Account Constant
export const ACCOUNTS_LOADING = 'ACCOUNTS_LOADING';
export const RESET_TIMEZONE = 'RESET_TIMEZONE';


// STORE CONSTANTS

export const FETCH_STORE_LIST = 'FETCH_STORE_LIST';
export const STORE_LOADING = 'STORE_LOADING';
export const STORE_DETAIL = 'STORE_DETAIL';
export const UPDATE_STORE = 'UPDATE_STORE';
export const CHANGE_STORE_ACTIVITY = 'CHANGE_STORE_ACTIVITY';

export const UPDATE_MAP_IMAGE = 'UPDATE_MAP_IMAGE';
export const UPDATE_STORE_IMAGE = 'UPDATE_STORE_IMAGE';
export const UPDATE_EMAIL_IMAGE = 'UPDATE_EMAIL_IMAGE';

// EMPLOYEE CONSTANTS
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const EMPLOYEE_LOADING = 'EMPLOYEE_LOADING';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';


// PRODUCTS CONSTANTS
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const FETCH_ALL_PRODUCTS_LIST = 'FETCH_ALL_PRODUCTS_LIST';
export const FETCH_FRAMES_NAME_LIST = 'FETCH_FRAMES_NAME_LIST';
export const FRAME_NAME_DETAIL = 'FRAME_NAME_DETAIL';
export const DELETE_FRAME_NAME = 'DELETE_FRAME_NAME';

export const FETCH_FRAMES_COLOR_LIST = 'FETCH_FRAMES_COLOR_LIST';
export const FRAME_COLOR_DETAIL = 'FRAME_COLOR_DETAIL';
export const DELETE_FRAME_COLOR = 'DELETE_FRAME_COLOR';
export const FETCH_PRODUCTS_DETAIL = 'FETCH_PRODUCTS_DETAIL';
export const MANAGE_PRODUCT = 'MANAGE_PRODUCT'

export const FETCH_ALL_FRAMES_NAME_LIST= 'FETCH_ALL_FRAMES_NAME_LIST';
export const FETCH_ALL_FRAMES_COLOR_LIST= 'FETCH_ALL_FRAMES_COLOR_LIST';
export const FETCH_ALL_FRAMES_SIZES = 'FETCH_ALL_FRAMES_SIZES';
export const RESET_FRAMES_SIZES = 'RESET_FRAMES_SIZES';
export const FETCH_GALLERY_DETAIL = 'FETCH_GALLERY_DETAIL';
export const SHOW_ON_APP = 'SHOW_ON_APP';











